# Site settings
title: Pizza de Dados
description: O primeiro e o mais querido podcast sobre ciência de dados no Brasil
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pizzadedados.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pizza de Dados
user_description: O primeiro e o mais querido podcast sobre ciência de dados no Brasil
user_title: Pizza de Dados
email: pizzadedados@gmail.com
twitter_username: pizzadedados
facebook: pizzadedados
youtube: pizzadedados
instagram: pizzadedados
github_username: pizzadedados
# gplus_username:
logo_path: "/assets/img/signo.png"

# Pizzaiolas photos
lele_photo: "https://res.cloudinary.com/diqouskfp/image/upload/v1682709537/site/leticia_vp9zjb.jpg"
jess_photo: "hhttps://res.cloudinary.com/diqouskfp/image/upload/v1682709538/site/jessica_bz6tho.jpg"
ceci_photo: "https://res.cloudinary.com/diqouskfp/image/upload/v1682709538/site/ceci_doz1mc.jpg"

# Google-analytics
google-analytics:
  id: "G-NMXLYV8B0S"

include: ['robots.txt']

exclude: ['package.json', 'src' , 'node_modules']
plugins_dir:
  - jekyll-redirect-from
