# Site settings
title: Pizza de Dados
description: O primeiro e o mais querido podcast sobre ciência de dados no Brasil
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pizzadedados.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pizza de Dados
user_description: O primeiro e o mais querido podcast sobre ciência de dados no Brasil
user_title: Pizza de Dados
email: pizzadedados@gmail.com
twitter_username: pizzadedados
facebook: pizzadedados
youtube: pizzadedados
instagram: pizzadedados
github_username: pizzadedados
# gplus_username:
logo_path: "/assets/img/signo.png"

# Pizzaiolos photos
lele_photo: "https://avatars.githubusercontent.com/u/7255297?v=4"
jess_photo: "https://avatars.githubusercontent.com/u/6595551" 
gust_photo: ""

# Google-analytics
google-analytics:
  id: "UA-106178084-2"

include: ['robots.txt']

exclude: ['package.json', 'src' , 'node_modules']
plugins_dir:
  - jekyll-redirect-from
