# Site settings
title: Pizza de Dados
description: O primeiro e o mais querido podcast sobre ciência de dados no Brasil
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pizzadedados.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pizza de Dados
user_description: O primeiro e o mais querido podcast sobre ciência de dados no Brasil
user_title: Pizza de Dados
email: pizzadedados@gmail.com
twitter_username: pizzadedados
facebook: pizzadedados
youtube: pizzadedados
instagram: pizzadedados
github_username: pizzadedados
# gplus_username:
logo_path: "/assets/img/signo.png"

# Pizzaiolos photos
lele_photo: "https://lh3.googleusercontent.com/-SOWIGDQ-BGM/XEcYjC2F_hI/AAAAAAAAgUQ/3r1h8P6E1kQPXGdcgoEKxtm6GpJNS7PLQCEwYBhgL/w280-h278-p/perfil.jpg"
jess_photo: "https://i.imgur.com/DbhFvDr.jpg"
gust_photo: "https://i.imgur.com/jK2yR0q.jpg"

# Google-analytics
google-analytics:
  id: "G-NMXLYV8B0S"

include: ['robots.txt']

exclude: ['package.json', 'src' , 'node_modules']
plugins_dir:
  - jekyll-redirect-from
